//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Catedra_PED.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta_Productos
    {
        public int id_VentaIDEN { get; set; }
        public Nullable<int> id_Venta { get; set; }
        public Nullable<int> id_Produc { get; set; }
        public string cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
